{% set name = "tmuxp" %}
{% set version = "1.49.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 162a761e7c086b4de48626252f9164855a3ce284b43920fd7fbf5b1052c1a0d7

build:
  # Seeing weird errors like the following on Windows, along with weird encoding.
  # https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/c-runtime-error-r6033?view=msvc-170
  script:
    - {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - colorama >=0.3.9
    - pyyaml >=6.0
    - libtmux >=0.39
    - __unix

test:
  requires:
    - python {{ python_min }}
    - pip
  files:
    - session.yaml
  commands:
    - pip check
    - tmuxp --version                  # [unix]
    - tmuxp load -d -y ./session.yaml  # [unix]

about:
  home: https://tmuxp.git-pull.com/
  doc_url: https://tmuxp.git-pull.com/
  dev_url: https://github.com/tmux-python/tmuxp
  summary: Session manager for tmux, build on libtmux
  description: |
    Session manager for tmux, which allows users to save and load tmux sessions through simple
    configuration files.
    Powered by libtmux.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AntoinePrv
    - tony
