{% set name = "tmuxp" %}
{% set version = "1.47.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d863a08450fa5956f54af64578121c38c0693961f2154a4674faaa9fe8dcf87

build:
  # Seeing weird errors like the following on Windows, along with weird encoding.
  # https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/c-runtime-error-r6033?view=msvc-170
  script:
    - {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0
  run:
    - python >=3.8
    - colorama >=0.3.9
    - pyyaml >=6.0
    - libtmux >=0.36
    - __unix

test:
  requires:
    - pip
  files:
    - session.yaml
  commands:
    - pip check
    - tmuxp --version                  # [unix]
    - tmuxp load -d -y ./session.yaml  # [unix]

about:
  home: https://tmuxp.git-pull.com/
  doc_url: https://tmuxp.git-pull.com/
  dev_url: https://github.com/tmux-python/tmuxp
  summary: Session manager for tmux, build on libtmux
  description: |
    Session manager for tmux, which allows users to save and load tmux sessions through simple
    configuration files.
    Powered by libtmux.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AntoinePrv
    - tony
